[1.0-dev] Add an example where we toggle between view and edit
memspace/zefyr pull request #411
Opened 2020-09-30 20:08 UTC by cgestes

It helps catching bugs when we change Zefyr properties, I believe this one is a common usecase.

It is an example of a readonly view.

2020-10-01 03:56 UTC, pulyaevskiy requested changes
Thanks, this is nice! Have some comments around the structure and contents, but otherwise looks good.

Please take a look.

2020-10-01 03:56 UTC, pulyaevskiy commented on packages/zefyr/example/lib/src/home.dart
> +          title: Text('¶   Edit button', style: itemStyle),
Let's call it "Read only view"?

2020-10-01 03:56 UTC, pulyaevskiy commented on packages/zefyr/example/lib/src/home.dart
> +          title: Text('¶   Edit button', style: itemStyle),
Also, create a new section "BASICS" in this menu and probably make it the top one. Move this example to the BASICS section, of course.

2020-10-01 03:56 UTC, pulyaevskiy commented on packages/zefyr/example/lib/src/edit_button_layout.dart
> +      documentFilename: 'layout_expanded.note',
This needs to be specific to the example, e.g. "basics_read_only_view.note".

You don't have to create the actual document it'll default to an "Empty asset". But if you feel adventurous you can create and edit it using following steps:

1. Run the app in desktop mode.
2. On the home screen click on the "cog" icon next to Zefyr title
3. Paste path to the assets folder. E.g. `/path/to/zefyr/packages/zefyr/example/assets`.
4. Save the dialog
5. Open the new example, you'll see default content in the editor "Empty asset"
6. Type in whatever example description you think would be appropriate.
7. Click on the "Save" button in the top-right corner
8. Done

2020-10-01 03:56 UTC, pulyaevskiy commented on packages/zefyr/example/lib/src/edit_button_layout.dart
> +    );
Can simplify this to:

```dart
    return ZefyrEditor(
      controller: controller,
      focusNode: _focusNode,
      expands: true,
      readOnly: !_edit,
      showCursor: _edit,
      padding: EdgeInsets.symmetric(horizontal: 8),
    );
```

2020-10-01 03:56 UTC, pulyaevskiy commented on packages/zefyr/example/lib/src/forms_decorated_field.dart
> +      showToolbar: false,
Thanks!

2020-10-01 08:52 UTC, cgestes commented
Will makes the changes :)

2020-10-01 21:12 UTC, cgestes commented
Should be fine now. Tell me if it needs more changes.

PS: Wow Linux support is working really well :+1:

2020-10-02 04:14 UTC, pulyaevskiy approved these changes
LGTM, thanks!

2020-10-02 04:15 UTC, merged