Added support for underline and strikethrough style
memspace/zefyr pull request #429
Opened 2020-11-11 19:29 UTC by Amir-P

2020-11-11 21:26 UTC, cgestes requested changes

2020-11-11 21:26 UTC, cgestes commented on packages/zefyr/example/ios/Runner.xcodeproj/project.pbxproj
>  				"${PODS_ROOT}/../Flutter/Flutter.framework",
Are those changes requires?

2020-11-11 21:26 UTC, cgestes commented on packages/zefyr/example/ios/Podfile.lock
> +  - path_provider_linux (0.0.1):
Are the changes to this file required?

2020-11-11 21:26 UTC, cgestes commented on packages/zefyr/pubspec.yaml
> -  notus: ^1.0.0-dev
This needs to be dropped

2020-11-11 21:26 UTC, cgestes commented on packages/zefyr/lib/src/widgets/controller.dart
> +  List<String> get _insertionToggleableStyleKeys => [
Can you move this outside the class? Seems static.

2020-11-11 21:27 UTC, cgestes commented
Btw, I am not the maintainer, just helping here :)

2020-11-13 12:05 UTC, cgestes reviewed
Looks good for me except the comment.

Let's wait for @pulyaevskiy review

2020-11-13 12:05 UTC, cgestes commented on packages/zefyr/lib/src/widgets/controller.dart
> +List<String> get _insertionToggleableStyleKeys => [
Can you turn it into a variable?

2020-11-13 12:19 UTC, cgestes commented
Also we may have to bump Notus version so that the test passes. I dont know how it works.

2020-11-13 16:46 UTC, Amir-P commented on packages/zefyr/lib/src/widgets/controller.dart
> +List<String> get _insertionToggleableStyleKeys => [
Done 👍

2020-11-14 06:09 UTC, pulyaevskiy commented
Thanks for taking time to submit this PR. I will take a look at it over this weekend.

2020-11-15 04:49 UTC, pulyaevskiy reviewed
This LGTM overall, just have a naming comment. PTAL.

Thanks again for taking time to work on this.

2020-11-15 04:49 UTC, pulyaevskiy commented on packages/notus/lib/src/document/attributes.dart
> +  static const strike = _StrikeAttribute();
I feel like it maybe better to name this `strikethrough` for consistency sake (as well as all other occurrences of this name here). WDYT?

2020-11-15 08:56 UTC, Amir-P commented on packages/notus/lib/src/document/attributes.dart
> +  static const strike = _StrikeAttribute();
Yes, you're right I've renamed it.

2020-11-15 17:03 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/theme.dart
> +  final TextStyle strike;
Looks like this needs to be renamed as well.

2020-11-15 18:32 UTC, Amir-P commented on packages/zefyr/lib/src/widgets/theme.dart
> +  final TextStyle strike;
Totally forgot about that! It's Done.

2020-11-15 19:23 UTC, pulyaevskiy approved these changes
Nicely done, thanks again, LGTM now!

2020-11-15 19:23 UTC, merged

2020-11-25 09:42 UTC, lisadeng commented
@cgestes @pulyaevskiy

2020-11-25 10:57 UTC, cgestes commented
Hi,

cool for the features.

If you want to work on a local version of zefyr you can add this to your pubspec.yaml:

```
dependencies:
  zefyr:
    path: ../zefyr/packages/zefyr
```

You will have to amend the path to match your local checkout.

Formatting features may be straightforward.

The others features need proper separated issues to discuss how to do it :)

2020-11-26 01:23 UTC, lisadeng commented
> Hi,
> 
> cool for the features.
> 
> If you want to work on a local version of zefyr you can add this to your pubspec.yaml:
> 
> ```
> dependencies:
>   zefyr:
>     path: ../zefyr/packages/zefyr
> ```
> 
> You will have to amend the path to match your local checkout.
> 
> Formatting features may be straightforward.
> 
> The others features need proper separated issues to discuss how to do it :)

Hi cgestes,
Noted with many thanks.