Migrated Notus to null safety
memspace/zefyr pull request #510
Opened 2021-06-22 06:19 UTC by Amir-P

I've migrated Notus to null safety and applied some linter suggestions.

2021-06-23 03:55 UTC, pulyaevskiy requested changes
Thanks, this looks good, just have some minor nits. Please take a look.

Also there looks like an extra binary file committed in this PR, which I think we don't need.

2021-06-23 05:31 UTC, Amir-P commented on packages/notus/lib/src/document/attributes.dart
> +    var typedOther = other;
Correct. I will remove all of the unnecessary statements like this.

2021-06-23 05:37 UTC, Amir-P commented on packages/notus/lib/src/document/leaf.dart
> +      node.next?.retain(0, remaining, style);
It's true that if `node.next` is null we won't even reach this statement but I prefer to not force non-nullability whenever is possible. It's more of a personal preference of mine so I will force non-nullability in all the similar cases.

2021-06-23 05:47 UTC, Amir-P commented on packages/notus/lib/src/heuristics/insert_rules.dart
> -    }
The `next` here is not nullable since the `DeltaIterator.next` return type is `Operation`. So this condition always results false.

2021-06-24 04:23 UTC, pulyaevskiy commented on packages/notus/lib/src/heuristics/insert_rules.dart
> -    }
Good catch, thanks!

2021-06-24 04:27 UTC, pulyaevskiy approved these changes
LGTM, thanks!

2021-06-24 04:28 UTC, merged