Migration of Zefyr to null-safety
memspace/zefyr pull request #515
Opened 2021-07-09 13:56 UTC by Amir-P

I tried to read comments and source code to take the best decisions. Also one of the controller tests is failing right now because of the #513. I will update the Notus version after #514 gets accepted.

2021-07-10 04:19 UTC, pulyaevskiy commented
Notus is now updated. I'll be looking at this PR over the weekend. Thanks!

2021-07-10 06:39 UTC, Amir-P commented
> Notus is now updated. I'll be looking at this PR over the weekend. Thanks!

I just updated Notus version in dependencies. All tests are passing now.

2021-07-12 01:32 UTC, pulyaevskiy requested changes
Thanks, this is great. Have a few suggestions. PTAL!

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/rendering/paragraph_proxy.dart
> +    required TextHeightBehavior? textHeightBehavior,
Let's change non-nullability and `required` of these fields to match requirements of `TextPainter`. E.g. 

* remove `required` on `textHeightBehavior`, `locale`, `strutStyle`, `textDirection`, etc.
* `textStyle` change to non-null (this is not exactly guided by TextPainter, but we definitely need it in Zefyr)
* `strutStyle` change to nullable

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/rendering/paragraph_proxy.dart
> +  RenderParagraph? get child => super.child as RenderParagraph?;
We should make it non-nullable, I think.

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/baseline_proxy.dart
> +  final EdgeInsets? padding;
Should make both non-null here as well.

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editable_text_block.dart
> +            .copyWith(color: theme.code?.style.color?.withOpacity(0.4)),
I think we should make all theming accessors above non-nullable. If a theme does not provide any of these we should fail early.

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editable_text_block.dart
> +            .copyWith(color: theme.code?.style.color?.withOpacity(0.4)),
Similarly for all code that accesses theme data below as well.

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editable_text_block.dart
> +    this.style,
We should keep style required and non-null.

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editable_text_block.dart
> +    this.style,
Similarly for `_BulletPoint` below.

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
> +      focusNode: widget.focusNode!,
This is strange. Widget's focusNode is nullable so this can fail. Let's make widget's field non-null.

2021-07-12 01:32 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
> +      _editorKey.currentContext?.findRenderObject() as RenderEditor;
I don't understand how this works. It may result in null but the return type is non-nullable?

2021-07-12 17:36 UTC, Amir-P commented on packages/zefyr/lib/src/rendering/editable_text_line.dart
> +  RenderContentProxyBox? _body;
But in some functions there are logics for handling situations where body is null. I think there are some cases where body might be null right?

2021-07-12 17:42 UTC, Amir-P commented on packages/zefyr/lib/src/rendering/paragraph_proxy.dart
> +  RenderParagraph? get child => super.child as RenderParagraph?;
`RenderParagraphProxy` constructor has `RenderParagraph? child` as input. So the child can be null unless we make that non-nullable too. Let me know what you think.

2021-07-12 17:48 UTC, Amir-P commented on packages/zefyr/lib/src/widgets/editable_text_block.dart
> +            .copyWith(color: theme.code?.style.color?.withOpacity(0.4)),
So why don't we make `ZefyrThemeData` variables non-nullable? This way instead of runtime errors, users will get analyzer and compile errors.

2021-07-12 17:58 UTC, Amir-P commented on packages/zefyr/lib/src/widgets/editor.dart
> +      focusNode: widget.focusNode!,
Yes it occurred to me too but I thought fixing it is out of this commits scope. If you check `ZefyrEditor.focusNode` comment it clearly says it can be null and in that case editor will create an instance (which is not the thing happening). I think we can adopt the Flutter's native widgets behavior (`focusNode` is nullable and the editor will create it's own instance if it's null). What do you think?

2021-07-12 18:01 UTC, Amir-P commented on packages/zefyr/lib/src/widgets/editor.dart
> +      _editorKey.currentContext?.findRenderObject() as RenderEditor;
I will force non-nullability on `_editorKey.currentContext`. It's going to throw exception anyway.

2021-07-12 18:06 UTC, Amir-P commented on packages/zefyr/lib/src/rendering/paragraph_proxy.dart
> +  RenderParagraph? get child => super.child as RenderParagraph?;
After checking the usages of `RenderParagraphProxy`, the `child` is never being passed when creating an instance of it.

2021-07-17 19:03 UTC, pulyaevskiy commented on packages/zefyr/lib/src/rendering/editable_text_line.dart
> +  RenderContentProxyBox? _body;
I looked through the usages and got an impression the body should always be provided. Could you point me at the source where you think it's assumed to be nullable?

2021-07-17 19:05 UTC, pulyaevskiy commented on packages/zefyr/lib/src/rendering/paragraph_proxy.dart
> +  RenderParagraph? get child => super.child as RenderParagraph?;
Oh wait, is `super.child` also nullable? If so then ignore my comment.

2021-07-17 19:05 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editable_text_block.dart
> +            .copyWith(color: theme.code?.style.color?.withOpacity(0.4)),
I agree, let's make all fields in `ZefyrThemeData` non-nullable.

2021-07-17 19:08 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
> +      focusNode: widget.focusNode!,
Yeah, I think I meant to implement the same logic, but haven't gotten to it yet. But feel free to ignore it for this PR (maybe leave a TODO), we can tackle it in a follow up, to keep things simpler here (this is already very hard to review due to the size).

2021-07-18 18:46 UTC, Amir-P commented on packages/zefyr/lib/src/rendering/editable_text_line.dart
> +  RenderContentProxyBox? _body;
Take a look at `editable_text_line.dart:161`, `editable_text_line.dart:529`, `editable_text_line.dart:543`, `editable_text_line.dart:554`, `editable_text_line.dart:567`, `editable_text_line.dart:590`, `editable_text_line.dart:642`. @pulyaevskiy

2021-07-19 03:59 UTC, pulyaevskiy commented on packages/zefyr/lib/src/rendering/editable_text_line.dart
> +  RenderContentProxyBox? _body;
Ah, ok, you're right. This is in render objects. Yeah, Flutter engine may detach children at any point so we can't really expect body to always be set.

2021-07-19 04:05 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editable_text_block.dart
> +    return VerticalSpacing(top: top ?? 0, bottom: bottom ?? 0);
Just curious why not leave top and bottom non-nullable?

2021-07-19 04:06 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editable_text_line.dart
> +import 'package:zefyr/src/rendering/editable_box.dart';
This needs to use relative path as everywhere else.

2021-07-19 04:13 UTC, pulyaevskiy reviewed
Thanks again, just have a couple more comments. But otherwise this looks good to merge. Let me know if you still plan to push more changes or ready for this to land.

2021-07-19 04:13 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
> +      _editorKey.currentContext?.findRenderObject() as RenderEditor;
I assume this still needs to be updated?

2021-07-19 05:24 UTC, Amir-P commented on packages/zefyr/lib/src/widgets/editor.dart
> +      _editorKey.currentContext?.findRenderObject() as RenderEditor;
You're right I totally forgot about this. Will fix in another commit in a few moments.

2021-07-19 05:28 UTC, Amir-P commented on packages/zefyr/lib/src/widgets/editable_text_block.dart
> +    return VerticalSpacing(top: top ?? 0, bottom: bottom ?? 0);
Because `lineSpacing` is optional and I'm not sure if all the cases are being covered by conditions in lines 142 to 151 of `editable_text_block.dart`.

2021-07-19 05:41 UTC, Amir-P commented
I just pushed another commit with changes you suggested and I don't have any other changes in mind. If it was ok please merge it into the `1.0-dev`. Thanks. @pulyaevskiy

2021-07-20 04:22 UTC, pulyaevskiy approved these changes
LGTM!

2021-07-20 04:22 UTC, merged