Fixed #522
memspace/zefyr pull request #523
Opened 2021-08-04 19:34 UTC by Amir-P

2021-08-05 04:08 UTC, pulyaevskiy requested changes
This looks good overall. Just have one suggestion.

2021-08-05 04:08 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
> +      oldWidget.focusNode?.removeListener(_handleFocusChanged);
What if `widget.focusNode` is set, `oldWidget.focusNode` is null and we have an internal instance currently?

Our internal focusNode will not be cleaned up in this case, right?

I think I'd prefer to refactor this logic as well as `effectiveFocusNode` not rely on `_focusNode ?? FocusNode()` in `effectiveFocusNode`. Instead initialize focus not here in `didUpdateWidget`.

I feel like the way it works now is a bit fragile and can lead to unexpected issues which would be hard to track and fix.

WDYT?

2021-08-05 06:21 UTC, Amir-P commented on packages/zefyr/lib/src/widgets/editor.dart
> +      oldWidget.focusNode?.removeListener(_handleFocusChanged);
You're right. I was thinking that our internal `focusNode` is going to be disposed when the state disposes but I missed the fact that the listener will still be called in that case.

2021-08-06 04:14 UTC, pulyaevskiy approved these changes
LGTM, just a few more nits. PTAL!

2021-08-06 04:14 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
> +      }
This `if` statement is unnecessary I think. Also we still need to take care of the listener on the internal instance. This can be simplified as:

```dart
_focusNode?.removeListener(_handleFocusChanged);
_focusNode?.dispose();
  // below is not _strictly_ required, but I prefer to not leave any pointers to 
  // disposed objects around, and let the runtime garbage collect them.
_focusNode = null; 
```

2021-08-06 04:14 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
>    //TODO: Make it optional and create an instance if it's null
This todo is addressed by this PR right?

2021-08-06 04:14 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
> +  void _createInternalFocusNodeIfRequired() {
nit: I usually use `IfNeeded` suffix instead of `IfRequired`. Would be nice to follow the pattern here as well for consistency.

2021-08-06 08:29 UTC, Amir-P commented
I've applied all your suggestions @pulyaevskiy

2021-08-07 03:37 UTC, pulyaevskiy approved these changes
LGTM, thanks!

2021-08-07 03:37 UTC, merged