Bring into view upon selection extension
memspace/zefyr pull request #527
Opened 2021-08-07 21:16 UTC by amantoux

When extending selection, have scroll controller jump to the most appropriate offset to display selection extension

Before

https://user-images.githubusercontent.com/17318211/128613932-5ff7715e-559f-4d0b-a055-1ccf28af240a.mov

After

https://user-images.githubusercontent.com/17318211/128613963-90346052-aa06-488d-b63d-bd4962ea161f.mov

2021-08-07 21:21 UTC, amantoux commented
@pulyaevskiy,  can you please have a look?

2021-08-08 05:17 UTC, pulyaevskiy requested changes
This is a much needed improvement, thanks! I left some suggestions, please take a look.

2021-08-08 05:17 UTC, pulyaevskiy commented on packages/zefyr/lib/src/rendering/editor.dart
> +        targetChild.cursorPainter?.getPixelPerfectCursorOffset(rect);
I was a bit confused about why you decided to expose `cursorPainter` but I think I see why now.

I believe that we shouldn't need pixel-perfect offset here as it should only be relevant to painting (ensure the caret doesn't look blurry). This means we don't need to expose `cursorPainter`, as well as no need to make its `getPixelPerfectCursorOffset` public.

WDYT?

2021-08-08 05:17 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor.dart
> +  late ScrollController scrollController;
I think I'd prefer this to be read-only for the outside world. Similar to how over fields are defined.

Moreover, I think we can keep `_scrollController` completely private and only expose specific method on the state interface, e.g. `jumpTo(offset)`. Just encapsulate the details of scrolling inside the state object.

WDYT?

2021-08-08 05:53 UTC, amantoux commented on packages/zefyr/lib/src/rendering/editable_text_block.dart
> +import 'package:zefyr/src/rendering/cursor_painter.dart';
Ok
I've had some problems in the past when debugging when importing with relative path (only with async though)

2021-08-08 07:35 UTC, amantoux commented on packages/zefyr/lib/src/rendering/editor.dart
> +  Rect getLocalRectForCaret(TextPosition position) {
Do you have use cases in mind that would leverage on `RenderAbstractEditor` other than `RenderEditor`?

2021-08-08 07:35 UTC, amantoux commented on packages/zefyr/lib/src/rendering/editor.dart
> +        targetChild.cursorPainter?.getPixelPerfectCursorOffset(rect);
Yes, indeed, my bad

2021-08-08 07:50 UTC, amantoux commented on packages/zefyr/lib/src/widgets/editor.dart
> +  late ScrollController scrollController;
`scrollController` is also used in
```dart
RevealedOffset _getOffsetToRevealCaret(Rect rect, TextPosition position)
``` 
in `editor-selection-delegate-mixin`

state object could implement this behavior but it seems to be the responsibility of the mixin.
I can make it read-only though
WDYT?

2021-08-09 04:00 UTC, pulyaevskiy reviewed
Thanks again. Just one more suggestion.

2021-08-09 06:42 UTC, amantoux commented on packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart
> +    renderEditor.showOnScreen(rect: targetOffset.rect);
It bubbles up the rendering tree, to ensure that if a element is in a viewport that is itself in a viewport(etc), it shows on screen.
That said, I think we can remove
```dart
scrollController.jumpTo(targetOffset.offset);
```
(it is called in `editable_text.dart` by the Flutter team for some reason that I don't understand)

2021-08-09 06:44 UTC, amantoux commented on packages/zefyr/lib/src/rendering/editable_box.dart
> +  TextPosition? globalToLocalPosition(TextPosition position);
Yes I agree

2021-08-09 12:10 UTC, amantoux commented on packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart
> +    renderEditor.showOnScreen(rect: targetOffset.rect);
further thoughts:
`scrollController.jumpTo` complements behavior of `renderEditor.showOnScreen` in case line height is greater the scroll magnitude

2021-08-12 03:59 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart
> +    renderEditor.showOnScreen(rect: targetOffset.rect);
Thank you!

2021-08-12 04:03 UTC, pulyaevskiy approved these changes
LGTM, thank you!

2021-08-12 04:04 UTC, merged