iOS - Floating cursor
memspace/zefyr pull request #555
Opened 2021-11-14 11:13 UTC by amantoux

On iOS, ability to use virtual keyboard as a trackpad.

https://user-images.githubusercontent.com/17318211/141678553-4d7e6499-61e9-48c0-86d8-f845984db84d.mov

2021-11-14 17:52 UTC, amantoux commented on packages/zefyr/lib/src/rendering/cursor_painter.dart
> +
Floating painter responsible to drawing the cursor when floating mode is activated

2021-11-14 17:55 UTC, amantoux commented on packages/zefyr/lib/src/rendering/editable_text_line.dart
> +    var textPosition = _cursorController.isFloatingCursorActive
Paints regular cursor but also the background cursor when floating cursor is activated.
The background cursor shows the closest text position of the regular corresponding to the current floating cursor position should the latter be released

2021-11-14 17:59 UTC, amantoux commented on packages/zefyr/lib/src/rendering/editor.dart
> +
Floating cursor's painting is the responsibility of the render editor to ensure smoothness of the animation
The render editor now holds a reference to the cursor controller. It sets the closest text position `floatingCursorTextPosition` in the cursor controller. The latter will be read by `RenderEditableTextline` to paint the background cursor

2021-11-14 18:04 UTC, amantoux commented on packages/zefyr/lib/src/rendering/editor.dart
> +      final caretPrototype =
`RenderEditableBox` requires `getCaretPrototype`

2021-11-24 18:19 UTC, pulyaevskiy requested changes
Thank you! This LGTM overall, just have a few comments around docs. PTAL

2021-11-24 18:19 UTC, pulyaevskiy commented on packages/zefyr/lib/src/rendering/editor.dart
> +  void handleSelectionChange(
Why making this method public?

2021-11-24 18:19 UTC, pulyaevskiy commented on packages/zefyr/lib/src/rendering/editor.dart
> +      {double? resetLerpValue}) {
The original method definition in the abstract editor does not include `resetLerpValue`, is this intentional?
Would be useful to document what this argument does.

2021-11-24 18:19 UTC, pulyaevskiy commented on packages/zefyr/lib/src/widgets/editor_input_client_mixin.dart
> +  void onFloatingCursorResetTick() {
This would also benefit from a doc comment.

2021-11-25 08:13 UTC, amantoux commented on packages/zefyr/lib/src/rendering/editor.dart
> +  void handleSelectionChange(
For a wrong reason, thanks

2021-11-25 21:15 UTC, pulyaevskiy approved these changes
LGTM, thank you!

2021-11-25 21:16 UTC, merged